const DataBank = [
  {
    id: "CARRARA-SEMI-WHITE",
    Abrev: "SWM", // semi white
    name: "SEMI-WHITE-CARRARA",
    title: "CARRARA MARBLE FOR STEPS and more",
    singleImage: require("../images/semiWhiteCarrara.jpg").default,
    decorImg: require("../images/Carrara-marble-bathroom.jpg").default,
    slug: `CARRARA`,
    feature: true,
    images: [
      {
        original: require("../images/semiWhiteCarrara-1000x600.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara-250x150.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE MARBLE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-001",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREECE-SEMI-WHITE",
    Abrev: "SWM", // semi white
    name: "SEMI-WHITE-GREECE",
    title: "GREECE MARBLE FOR STEPS and more",
    singleImage: require("../images/SEMI-WHITE-GREECE-01.jpg").default,
    decorImg: require("../images/Greece-semiWhite-decor.jpg").default,
    slug: `GREECE`,
    feature: true,
    images: [
      {
        original: require("../images/semiWhiteCarrara.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "MAHOUNA",
    Abrev: "SWM", // semi white
    name: "MAHOUNA",
    title: "BEAUTIFUL MAHOUNA MARBLE FOR....",
    singleImage: require("../images/Mahouna-01.jpg").default,
    decorImg: require("../images/Mahouna-01.jpg").default,
    slug: `MAHOUNA`,
    feature: true,
    images: [
      {
        original: require("../images/Mahouna-01-1000x600.jpg").default,
        thumbnail: require("../images/Mahouna-01-250x150.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
  {
    id: "GREEN-INDIA",
    Abrev: "GREEN", // semi white
    name: "GREEN INDIA",
    title: "GREEN IDNIA MARBLE FOR STEPS and more",
    singleImage: require("../images/GREEN-INDIA-01.jpg").default,
    decorImg: require("../images/GREEN-INDIA-DECOR.jpg").default,
    slug: `GREEN INDIA`,
    feature: true,
    images: [
      {
        original: require("../images/GREEN-INDIA-01.jpg").default,
        thumbnail: require("../images/semiWhiteCarrara.jpg").default,
      },
      {
        original: "https://picsum.photos/id/1015/1000/600/",
        thumbnail: "https://picsum.photos/id/1015/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
      {
        original: "https://picsum.photos/id/1019/1000/600/",
        thumbnail: "https://picsum.photos/id/1019/250/150/",
      },
    ],
    idInfo: {
      Family: "Marble",
      Category: "SEMI-WHITE GREECE",
      Brand: "NMC-Stone-Building and Art",
      Model: "NMC-002",
      Products: "Tiles,Slabs,Steps & ForSteps",
      Use: "Vanity Tops/Interior Floors/Exterior Floors/Interior Walls/facades/Tables",
      Finition: "Polished/Flamed/Sand/Bouchardy",
      Thikness: "10-30",
      Incoterm: "EX-WORK/FOB/CFR",
      PaymentTerms: "L/C,CAD,CHEQUE,CASH",
      UpdateTime: "2021-07-02",
    },
    techInfo: {
      ApparentDensity: "2709 kg/m3",
      Porosity: "0,15%",
      SoundVelocity: "6470 m/s",
      CompressiveStrength: "143,9 Mpa",
      BendingStrength: "18,5 Mpa",
      AbrasionResistance: "average 2mm",
      FrostResistance: "more than 240 cycles",
    },
  },
];

export default DataBank;
